CREATE TABLE IF NOT EXISTS flight (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "number" bigint DEFAULT 0, 
    "city_departure" character varying(200) DEFAULT '',
    "city_arrival" character varying(200) DEFAULT '',
    "time_departure" timestamp(0) with time zone DEFAULT CURRENT_TIMESTAMP,
    "time_arrival" timestamp(0) with time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp(0) with time zone DEFAULT CURRENT_TIMESTAMP,
    "created_at" timestamp(0) with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT access_log_id_pkey PRIMARY KEY (id));